dellydel/med-manage-web

README.md

Testing deploy on approval

---

index.html

Updated page title from  Vite + React to Med Manage

Updated page title from  Vite + React to Med Manage

---

src/MenuItem.jsx
src/NavBar.jsx

Added page routing from left nav Menu

Added page routing from left nav Menu

---

src/pages/Home.jsx

refactored main menu centering

refactored main menu centering

---

src/components/MenuItem.jsx

Updated the Menu items in the required order

ordering of Navigation links

---

src/pages/Patients.jsx

Will be pushing more updates....this is a quick push for any one whose tasks depends on the AG Grid to start  work...

Added Patient Magt Initial AG Grid

---

src/components/MenuItem.jsx
src/pages/Admin.jsx

In-Patient button added

---

src/pages/Patients.jsx

As an Admin
I want to be able to view all Patients in pages of 10 records each using AG-Grid's built in pagination feature.

Patients - Pagination

---

src/pages/Employees.jsx

As an Admin
I want to be able to view all Employees in pages of 10 records each using AG-Grid's built in pagination feature.

Employee - Pagination

---

src/components/MenuItem.jsx
src/pages/Admin.jsx

Rename In-Patient to In-Service

Change in-Patient to In-Service

---

src/pages/Employees.jsx

Added updates with more records

added Employee Management - Grid Updates

---

src/pages/Patients.jsx

Patient management page-header

---

src/pages/Employees.jsx

Add header-Employee management

Add Employee table header

---

src/pages/Layout.jsx

Logo (already in project) linked to NextByteWeb.com
Logo height: 30px;

Added NextByte logo to link to NextByteWeb.com

---

src/App.jsx
src/pages/Employees.jsx
src/services/apiEmployees.js

Employee data retrieval from endpoint

Employee Management Page - Data Retrieval

---

src/App.jsx
src/pages/Patients.jsx
src/services/apiPatients.js

Data retrieval for patient management from endpoint

Patient Management Page - Data Retrieval

---

src/pages/Employees.jsx

Pagination to view 10 records per page

Pagination restored

---

src/components/Footer.jsx
src/pages/Layout.jsx

Powered by NextByte at the bottom centre of pages

Footer kept at the bottom of pages with content

---

src/components/action_buttons/EmployeeButtonsRenderer.jsx
src/pages/Employees.jsx

Added Employee Management Action buttons

---

src/pages/Patients.jsx

Added filter/ search functionality to Employee management table

Add filter/search functionality to patient Table

---

src/pages/Employees.jsx

Added filter/ search functionality to Employee management table

Employee Search/Filter functionality

---

src/components/action_buttons/PatientsButtonsRenderer.jsx
src/pages/Patients.jsx

Added Patient Management Page - Action Column

---

src/pages/AddEmployee.jsx
src/pages/Employees.jsx
src/pages/Patients.jsx
src/services/employees.js

New employee password and confirm password fields commented out purposefully

fix for missing patient name

---

src/components/Footer.jsx
src/pages/Layout.jsx

Logo height fixed at bottom

---

src/pages/AddEmployee.jsx

Modal button fixed

---

src/pages/AddPatient.jsx

Modal close button fixed for Add Patients page

Add Patient close button fixed

---

src/pages/Employees.jsx
src/pages/Patients.jsx

Changed Patients pagination page size values

---

src/pages/Employees.jsx

Changed pagination size values

Changed employee pagination size values

---

src/components/action_buttons/EmployeeButtonsRenderer.jsx
src/pages/AddEmployee.jsx
src/pages/Employees.jsx
src/services/employees.js

Employee management modified to accommodate update.

Edit employee details

---

package-lock.json
src/App.jsx
src/pages/Admin.jsx

Admin button menu functionality

Admin button functionality

---

src/components/action_buttons/PatientsButtonsRenderer.jsx
src/mutations/useAddPatientMutation.js
src/mutations/useUpdatePatientMutation.js
src/pages/PatientModalForm.jsx
src/pages/Patients.jsx
src/services/patients.js

Added patient management page edit functionality

Added patient management page edit functionality

---

src/components/action_buttons/ReAssignButton.jsx
src/pages/AssignClinician.jsx
src/pages/Patients.jsx
src/services/patients.js

Button text renders based on whether a clinician is assigned.

Assign to button text made dynamic

---

src/components/action_buttons/PatientsButtonsRenderer.jsx

Reduced patient mgtr action button sizes

Reduced patient mgtr action button sizes

---

src/pages/AssignClinician.jsx
src/pages/Employees.jsx
src/pages/Patients.jsx
src/services/employees.js
src/services/patients.js

Added Error handling to http requests

Added Error handling to http requests
